# Generated by Django 4.2.5 on 2023-09-10 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='Institution',
            new_name='institution',
        ),
    ]
