# Generated by Django 4.2.5 on 2023-09-12 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0003_donation_is_taken'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='taken_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='taken_time',
            field=models.TimeField(null=True),
        ),
    ]
